`timescale 1ns / 1ps

/*
Description:
    Implements a 32-input signed adder tree optimized for Xilinx DSP48E2
    slices. The architecture replaces a conventional binary adder tree with a
    flattened ternary (3-input) reduction tree, reducing the number of
    arithmetic stages and minimizing LUT utilization.

    The tree performs the summation of thirty-two 18-bit signed input values
    using four hierarchical layers of DSP-based adders:

        Layer 1 : 10 × 3-input adders
                  - Sums inputs in groups of three
                  - Produces ten 20-bit partial sums
                  - Inputs in_31 and in_32 remain unprocessed in this stage

        Layer 2 : 4 × 3-input adders
                  - Combines the Layer 1 partial sums
                  - The fourth adder processes the remaining partial sum
                    (L1_10) together with the two orphan inputs
                    (in_31 and in_32), which are sign-extended to match the
                    Layer 2 input width.
                  - Produces four 22-bit partial sums

        Layer 3 : 1 × 3-input adder
                  - Combines the first three Layer 2 outputs
                  - Produces one 24-bit partial sum

        Layer 4 : 1 × 2-input adder
                  - Adds the Layer 3 result to the remaining Layer 2 output
                  - Produces the final 25-bit accumulated sum

Inputs:
    in_1 ... in_32
        Thirty-two signed 18-bit input operands (Q8.9 fixed-point).

Outputs:
    conv25_1 ... conv25_10
        Intermediate Layer 1 partial sums converted back to 18-bit Q8.9 format.

    final_output
        Final accumulated 18-bit signed result in Q8.9 format.

Features:
    - Explicit DSP48E2 arithmetic implementation.
    - Flattened 3-input reduction tree (10 → 4 → 1 → 1).
    - Reduced arithmetic depth compared to a binary adder tree.
    - Efficient DSP utilization with minimal LUT-based arithmetic.
    - Preserves Q8.9 fixed-point representation throughout the accumulation.
------------------------------------------------------------------------------
*/

module adder_tree_10_4_1_1(

    // -------------------------------------------------------------------------
    // 32 signed input operands (18-bit Q8.9 fixed-point values).
    // These correspond to the 32 partial products generated by the preceding
    // convolution stage and serve as the inputs to the DSP-based adder tree.
    // -------------------------------------------------------------------------
    input  logic signed [17:0] in_1,  in_2,  in_3,  in_4,
    input  logic signed [17:0] in_5,  in_6,  in_7,  in_8,
    input  logic signed [17:0] in_9,  in_10, in_11, in_12,
    input  logic signed [17:0] in_13, in_14, in_15, in_16,
    input  logic signed [17:0] in_17, in_18, in_19, in_20,
    input  logic signed [17:0] in_21, in_22, in_23, in_24,
    input  logic signed [17:0] in_25, in_26, in_27, in_28,
    input  logic signed [17:0] in_29, in_30, in_31, in_32,

    // -------------------------------------------------------------------------
    // Final accumulated result produced by the four-stage DSP48E2 adder tree.
    // The output is truncated back to an 18-bit signed Q8.9 fixed-point value
    // for compatibility with the remaining convolution datapath.
    // -------------------------------------------------------------------------
    output logic signed [17:0] conv25_1,
    output logic signed [17:0] conv25_2,
    output logic signed [17:0] conv25_3,
    output logic signed [17:0] conv25_4,
    output logic signed [17:0] conv25_5,
    output logic signed [17:0] conv25_6,
    output logic signed [17:0] conv25_7,
    output logic signed [17:0] conv25_8,
    output logic signed [17:0] conv25_9,
    output logic signed [17:0] conv25_10,
    output logic signed [17:0] final_output
);

    // =========================================================================
    // Layer 1: 10 x 3-input adders  (18-bit in ? 20-bit out)
    // =========================================================================
    logic signed [19:0] L1_1, L1_2, L1_3, L1_4, L1_5;
    logic signed [19:0] L1_6, L1_7, L1_8, L1_9, L1_10;

    adder_layer1 layer_1__1  (.add_1(in_1),  .add_2(in_2),  .add_3(in_3),  .adder_out(L1_1)  );
    adder_layer1 layer_1__2  (.add_1(in_4),  .add_2(in_5),  .add_3(in_6),  .adder_out(L1_2)  );
    adder_layer1 layer_1__3  (.add_1(in_7),  .add_2(in_8),  .add_3(in_9),  .adder_out(L1_3)  );
    adder_layer1 layer_1__4  (.add_1(in_10), .add_2(in_11), .add_3(in_12), .adder_out(L1_4)  );
    adder_layer1 layer_1__5  (.add_1(in_13), .add_2(in_14), .add_3(in_15), .adder_out(L1_5)  );
    adder_layer1 layer_1__6  (.add_1(in_16), .add_2(in_17), .add_3(in_18), .adder_out(L1_6)  );
    adder_layer1 layer_1__7  (.add_1(in_19), .add_2(in_20), .add_3(in_21), .adder_out(L1_7)  );
    adder_layer1 layer_1__8  (.add_1(in_22), .add_2(in_23), .add_3(in_24), .adder_out(L1_8)  );
    adder_layer1 layer_1__9  (.add_1(in_25), .add_2(in_26), .add_3(in_27), .adder_out(L1_9)  );
    adder_layer1 layer_1__10 (.add_1(in_28), .add_2(in_29), .add_3(in_30), .adder_out(L1_10) );


    // -------------------------------------------------------------------------
    // Layer 1 partial sums.
    // -------------------------------------------------------------------------
    // Each output represents the sum of one group of three input operands,
    // converted back to an 18-bit Q8.9 value for debugging or observation.
    assign conv25_1  = L1_1 [17:0];
    assign conv25_2  = L1_2 [17:0];
    assign conv25_3  = L1_3 [17:0];
    assign conv25_4  = L1_4 [17:0];
    assign conv25_5  = L1_5 [17:0];
    assign conv25_6  = L1_6 [17:0];
    assign conv25_7  = L1_7 [17:0];
    assign conv25_8  = L1_8 [17:0];
    assign conv25_9  = L1_9 [17:0];
    assign conv25_10 = L1_10[17:0];

    // =========================================================================
    // Layer 2: 4 x 3-input adders  (20-bit in ? 22-bit out)
    // Group 4 handles the 2 orphan inputs (in_31, in_32) + L1_10
    // =========================================================================
    logic signed [21:0] L2_1, L2_2, L2_3;
    logic signed [21:0] L2_4;   // was [20:0] - fix width to match layer2

    adder_layer2 layer_2__1 (.add_1(L1_1),  .add_2(L1_2),  .add_3(L1_3),  .adder_out(L2_1));
    adder_layer2 layer_2__2 (.add_1(L1_4),  .add_2(L1_5),  .add_3(L1_6),  .adder_out(L2_2));
    adder_layer2 layer_2__3 (.add_1(L1_7),  .add_2(L1_8),  .add_3(L1_9),  .adder_out(L2_3));

    // Orphan group: L1_10 + in_31 + in_32
    // Sign-extend in_31, in_32 from 18-bit to 20-bit to match adder_layer2 IN_WIDTH
    logic signed [19:0] in_31_ext;
    assign in_31_ext = {{2{in_31[17]}}, in_31} ;   
   
    logic signed [19:0] in_32_ext ;
    assign in_32_ext = {{2{in_32[17]}}, in_32};

    adder_layer2 layer_2__4 (.add_1(L1_10), .add_2(in_31_ext), .add_3(in_32_ext), .adder_out(L2_4));

    // =========================================================================
    // Layer 3: 1 x 3-input adder  (22-bit in ? 24-bit out)
    // =========================================================================
    logic signed [23:0] L3;

    adder_layer3 layer_3 (
        .add_1(L2_1),
        .add_2(L2_2),
        .add_3(L2_3),
        .adder_out(L3)
    );

    // =========================================================================
    // Layer 4: 1 x 2-input adder  (24-bit + 22-bit ? 25-bit out)
    // =========================================================================
    logic signed [24:0] L4;

    adder_layer4 layer_4 (
        .add_1(L3),
        .add_2(L2_4),
        .adder_out(L4)
    );

    // =========================================================================
    // Truncate the 25-bit accumulated sum to the lower 18 bits to match the
    // required Q8.9 fixed-point output format used by the subsequent stages.
    // =========================================================================
    assign final_output = L4[17:0];

endmodule
