onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /conv_adder_shaaban_top_test/DATA_WIDTH
add wave -noupdate /conv_adder_shaaban_top_test/N_SHAABAN
add wave -noupdate /conv_adder_shaaban_top_test/MAC_OUT_W
add wave -noupdate /conv_adder_shaaban_top_test/INPUTS_PER_SHB
add wave -noupdate /conv_adder_shaaban_top_test/N_TREES
add wave -noupdate /conv_adder_shaaban_top_test/fin
add wave -noupdate /conv_adder_shaaban_top_test/fout
add wave -noupdate /conv_adder_shaaban_top_test/clk
add wave -noupdate /conv_adder_shaaban_top_test/rst
add wave -noupdate /conv_adder_shaaban_top_test/src_sel
add wave -noupdate /conv_adder_shaaban_top_test/conv_bias_param
add wave -noupdate /conv_adder_shaaban_top_test/mult_weight_param
add wave -noupdate /conv_adder_shaaban_top_test/add_weight_param
add wave -noupdate /conv_adder_shaaban_top_test/pixels_mapped
add wave -noupdate /conv_adder_shaaban_top_test/weights_mapped
add wave -noupdate /conv_adder_shaaban_top_test/spike_out
add wave -noupdate /conv_adder_shaaban_top_test/shaaban_spike_bus
add wave -noupdate /conv_adder_shaaban_top_test/tree
add wave -noupdate /conv_adder_shaaban_top_test/neuron
add wave -noupdate /conv_adder_shaaban_top_test/tap
add wave -noupdate -group LIF_SH_1 {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/LIF_ints/clk}
add wave -noupdate -group LIF_SH_1 {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/LIF_ints/arst_n}
add wave -noupdate -group LIF_SH_1 {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/LIF_ints/in_pool}
add wave -noupdate -group LIF_SH_1 {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/LIF_ints/spike}
add wave -noupdate -group LIF_SH_1 {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/LIF_ints/mem_reg}
add wave -noupdate -group LIF_SH_1 {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/LIF_ints/spike_reg}
add wave -noupdate -group LIF_SH_1 {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/LIF_ints/reset_val}
add wave -noupdate -group LIF_SH_1 {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/LIF_ints/mem_leak}
add wave -noupdate -group LIF_SH_1 {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/LIF_ints/new_mem}
add wave -noupdate -group LIF_SH_1 {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/LIF_ints/mem_input_add_trnuc}
add wave -noupdate -group LIF_SH_1 {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/LIF_ints/mem_input_add}
add wave -noupdate -group LIF_SH_1 {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/LIF_ints/spike_int}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_conv9_array/gen_conv_row[0]/gen_conv_col[0]/u_conv/PIXEL_W}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_conv9_array/gen_conv_row[0]/gen_conv_col[0]/u_conv/PROD_W}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_conv9_array/gen_conv_row[0]/gen_conv_col[0]/u_conv/OUT_W}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_conv9_array/gen_conv_row[0]/gen_conv_col[0]/u_conv/CLK}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_conv9_array/gen_conv_row[0]/gen_conv_col[0]/u_conv/P}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_conv9_array/gen_conv_row[0]/gen_conv_col[0]/u_conv/Q}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_conv9_array/gen_conv_row[0]/gen_conv_col[0]/u_conv/Pixel_Out}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_conv9_array/gen_conv_row[0]/gen_conv_col[0]/u_conv/chain}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_conv9_array/gen_conv_row[0]/gen_conv_col[0]/u_conv/P_final}
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_conv9_array/PIXEL_W
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_conv9_array/MAC_OUT_W
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_conv9_array/DATA_WIDTH
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_conv9_array/FRAC_BITS
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_conv9_array/clk
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_conv9_array/pixels_mapped
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_conv9_array/weights_mapped
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_conv9_array/mac_to_connect
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_conv9_array/mac_raw
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_1}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_2}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_3}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_4}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_5}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_6}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_7}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_8}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_9}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_10}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_11}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_12}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_13}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_14}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_15}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_16}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_17}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_18}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_19}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_20}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_21}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_22}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_23}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_24}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_25}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_26}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_27}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_28}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_29}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_30}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_31}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_32}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_1}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_2}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_3}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_4}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_5}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_6}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_7}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_8}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_9}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_10}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/final_output}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_1}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_2}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_3}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_4}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_5}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_6}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_7}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_8}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_9}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_10}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L2_1}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L2_2}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L2_3}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L2_4}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_31_ext}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_32_ext}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L3}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L4}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/DATA_WIDTH}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/conv_bias_relu_num}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/batch_norm_num}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/pool_num}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/clk}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/rst}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/conv_in}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/conv_bias}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/mult_wight}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/add_wight}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/spike}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/conv_bias_relu_out}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/batch_norm_out}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/max_pool_out}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/gen_shaaban_array[0]/u_shb/final_pool_out}
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/DATA_WIDTH
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/N_SHAABAN
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/INPUTS_PER_SHB
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/clk
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/rst
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/shb_bus
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/conv_bias_param
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/mult_weight_param
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/add_weight_param
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/spike_out
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_shaaban_array/shaaban_spike_bus
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/N_TREES
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/TAPS_PER_TREE
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/N_SHAABAN
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/INPUTS_PER_SHB
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/DATA_WIDTH
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/TOTAL_S1_INPUTS
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/TOTAL_TAPS
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/N_CORRECTION
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/clk
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/rst
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/src_sel
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/mac_in
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/shb_conv_bus
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/tree_tap
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/tree_final
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/s3_results
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/ext_sum_raw
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/ext_sum_correction
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/flat_s1
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/t}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_1}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_2}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_3}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_4}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_5}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_6}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_7}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_8}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_9}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_10}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_11}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_12}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_13}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_14}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_15}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_16}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_17}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_18}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_19}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_20}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_21}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_22}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_23}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_24}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_25}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_26}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_27}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_28}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_29}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_30}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_31}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_32}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_1}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_2}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_3}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_4}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_5}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_6}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_7}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_8}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_9}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/conv25_10}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/final_output}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_1}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_2}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_3}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_4}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_5}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_6}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_7}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_8}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_9}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L1_10}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L2_1}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L2_2}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L2_3}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L2_4}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_31_ext}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/in_32_ext}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L3}
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_trees[0]/u_tree/L4}
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/ext_sum_raw
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/ext_sum_correction
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/flat_s1
add wave -noupdate {/conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/gen_shb_bus[0]/src_s1}
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/shb_conv_bus
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/src_sel
add wave -noupdate /conv_adder_shaaban_top_test/dut/u_shaaban_adder_tree/u_connect/src_sel
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {60000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 190
configure wave -valuecolwidth 233
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {522721 ps}
