//////////////////////////////////////////////////////////////////////////////////////////////////
// Author    : Ahmad Khattab
// Date      : 5/17/26
// File      : fc1_layer.sv
// Status    : finalized
// Goal      : Fully-connected layer 1: 128 inputs -> 256 outputs + ReLU.
//             Uses 8 parallel MAC units with time-multiplexed dot-product
//             computation across 32 batches. Q7.10 fixed-point.
//             Weight deduplication: MAP indices in 8 BRAM36 (4Kx9 each),
//             unique weights (375 values) in combinational LUT ROM.
//             1-cycle BRAM pipeline: 129 cycles/batch, 4,128 total.
//////////////////////////////////////////////////////////////////////////////////////////////////

module fc1_layer #(
    parameter int DATA_WIDTH     = 18,
    parameter int FRAC_BITS      = 9,
    parameter int N_INPUTS       = 128,
    parameter int N_OUTPUTS      = 256,
    parameter int ACCUM_WIDTH    = 48,
    parameter int PARALLEL_MACS  = 8
)(
    input  logic                           clk,
    input  logic                           rst,

    input  logic signed [DATA_WIDTH-1:0]   fc_in  [0:N_INPUTS-1],
    input  logic                           start,

    output logic signed [DATA_WIDTH-1:0]   fc_out [0:N_OUTPUTS-1],
    output logic                           done,
    output logic                           busy
);

    // =========================================================================
    // Unique weight values — generated by gen_unique_includes.py
    // =========================================================================
    `include "UNIQUE_FC1_W.svh"

    // =========================================================================
    // Biases
    // =========================================================================
    localparam logic signed [DATA_WIDTH-1:0] FC1_BIAS [N_OUTPUTS] = '{
        18'h3FFE7, 18'h00000, 18'h0001F, 18'h0001B, 18'h00007, 18'h3FFFF, 18'h0001F,
        18'h00000, 18'h00000, 18'h00019, 18'h0001F, 18'h3FFFF, 18'h00013, 18'h3FFDB,
        18'h00040, 18'h00000, 18'h0002D, 18'h00000, 18'h00005, 18'h00002, 18'h3FFF6,
        18'h3FFF5, 18'h00000, 18'h00026, 18'h00016, 18'h3FFE8, 18'h00000, 18'h00000,
        18'h00000, 18'h0000C, 18'h00011, 18'h00002, 18'h3FFED, 18'h00000, 18'h3FFF7,
        18'h00000, 18'h3FFED, 18'h3FFEC, 18'h00018, 18'h3FFFE, 18'h0000F, 18'h00000,
        18'h0002A, 18'h00000, 18'h3FFFB, 18'h3FFFF, 18'h3FFE9, 18'h00024, 18'h3FFE8,
        18'h00000, 18'h00014, 18'h3FFE9, 18'h3FFE9, 18'h3FFDC, 18'h00002, 18'h00000,
        18'h3FFF0, 18'h00018, 18'h3FFFA, 18'h00000, 18'h3FFFA, 18'h00009, 18'h00000,
        18'h00000, 18'h00010, 18'h00018, 18'h00000, 18'h3FFE8, 18'h00001, 18'h00000,
        18'h3FFE0, 18'h00022, 18'h3FFF7, 18'h00035, 18'h00000, 18'h00000, 18'h3FFEE,
        18'h00000, 18'h00000, 18'h0002F, 18'h3FFEB, 18'h3FFFA, 18'h00000, 18'h00012,
        18'h3FFDF, 18'h3FFFF, 18'h00000, 18'h3FFE2, 18'h00004, 18'h00000, 18'h0002B,
        18'h0000F, 18'h00019, 18'h0001A, 18'h00013, 18'h00000, 18'h00016, 18'h00000,
        18'h00041, 18'h3FFED, 18'h3FFFC, 18'h00000, 18'h00000, 18'h3FFFB, 18'h3FFE6,
        18'h0001B, 18'h3FFFD, 18'h0001A, 18'h3FFFC, 18'h00000, 18'h3FFD5, 18'h3FFEA,
        18'h00000, 18'h3FFE1, 18'h00006, 18'h00000, 18'h3FFEB, 18'h3FFED, 18'h00022,
        18'h0000D, 18'h00009, 18'h3FFEA, 18'h3FFE7, 18'h3FFE9, 18'h00002, 18'h00000,
        18'h0000C, 18'h3FFF6, 18'h3FFFF, 18'h3FFE9, 18'h3FFFD, 18'h00006, 18'h00018,
        18'h00000, 18'h3FFF4, 18'h0000A, 18'h3FFF3, 18'h00007, 18'h3FFFF, 18'h00000,
        18'h00000, 18'h3FFE3, 18'h3FFF6, 18'h3FFFC, 18'h3FFF6, 18'h00000, 18'h00027,
        18'h00003, 18'h0000A, 18'h0000B, 18'h00001, 18'h00000, 18'h00000, 18'h00008,
        18'h3FFDC, 18'h3FFF6, 18'h00000, 18'h00022, 18'h00000, 18'h00023, 18'h3FFEA,
        18'h3FFE0, 18'h3FFE1, 18'h00012, 18'h3FFF7, 18'h0001B, 18'h3FFE7, 18'h00017,
        18'h00000, 18'h00000, 18'h00007, 18'h00014, 18'h3FFE0, 18'h0000B, 18'h3FFFA,
        18'h3FFFE, 18'h3FFF4, 18'h00000, 18'h0000C, 18'h0000C, 18'h0001E, 18'h00014,
        18'h0001C, 18'h3FFF4, 18'h00000, 18'h3FFE5, 18'h3FFFC, 18'h00031, 18'h3FFE2,
        18'h3FFDC, 18'h00034, 18'h3FFE5, 18'h0000A, 18'h3FFFF, 18'h00000, 18'h3FFFD,
        18'h3FFF6, 18'h00027, 18'h00000, 18'h00010, 18'h00017, 18'h0000C, 18'h00000,
        18'h3FFF1, 18'h00000, 18'h3FFF1, 18'h3FFFD, 18'h00000, 18'h3FFFE, 18'h3FFDB,
        18'h0001E, 18'h00005, 18'h3FFFC, 18'h3FFFC, 18'h3FFFD, 18'h00000, 18'h00010,
        18'h3FFCC, 18'h0001A, 18'h3FFDF, 18'h00016, 18'h00006, 18'h3FFED, 18'h00000,
        18'h3FFCD, 18'h00000, 18'h00028, 18'h3FFFF, 18'h0001C, 18'h00017, 18'h3FFEE,
        18'h0000A, 18'h0000B, 18'h0000A, 18'h0000D, 18'h3FFE5, 18'h0001B, 18'h00035,
        18'h00003, 18'h00007, 18'h0002C, 18'h00000, 18'h0001F, 18'h0000D, 18'h0000A,
        18'h3FFE1, 18'h00015, 18'h00000, 18'h0000F, 18'h0002A, 18'h3FFFF, 18'h00002,
        18'h00006, 18'h00005, 18'h00000, 18'h3FFF6
    };

    // =========================================================================
    // BRAM: 8 separate BRAMs for MAP indices
    //   Each BRAM: 4096 entries x 9 bits → BRAM36 in SDP 4Kx9 mode
    //   MAC lane m stores MAP for neurons [m, m+8, m+16, ..., m+248]
    //   Address: {batch_idx[4:0], input_idx[6:0]} = 12 bits per entry
    // =========================================================================
    localparam int MAP_BITS      = 9;
    localparam int BRAM_DEPTH    = N_INPUTS * (N_OUTPUTS / PARALLEL_MACS);  // 4096
    localparam int NUM_BATCHES   = N_OUTPUTS / PARALLEL_MACS;                // 32
    localparam int BATCH_BITS    = $clog2(NUM_BATCHES);
    localparam int BATCH_CYCLES  = N_INPUTS + 1;     // 129: 1 setup + 128 MAC
    localparam int CYCLE_BITS    = $clog2(BATCH_CYCLES);
    localparam int INPUT_BITS    = $clog2(N_INPUTS);

    // Per-MAC BRAM declarations
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc1_map_bram_0 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc1_map_bram_1 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc1_map_bram_2 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc1_map_bram_3 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc1_map_bram_4 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc1_map_bram_5 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc1_map_bram_6 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc1_map_bram_7 [0:BRAM_DEPTH-1];

    initial begin
        $readmemh("fc1_map_bram_0.mem", fc1_map_bram_0);
        $readmemh("fc1_map_bram_1.mem", fc1_map_bram_1);
        $readmemh("fc1_map_bram_2.mem", fc1_map_bram_2);
        $readmemh("fc1_map_bram_3.mem", fc1_map_bram_3);
        $readmemh("fc1_map_bram_4.mem", fc1_map_bram_4);
        $readmemh("fc1_map_bram_5.mem", fc1_map_bram_5);
        $readmemh("fc1_map_bram_6.mem", fc1_map_bram_6);
        $readmemh("fc1_map_bram_7.mem", fc1_map_bram_7);
    end

    // =========================================================================
    // FSM
    // =========================================================================
    typedef enum logic [1:0] {
        ST_IDLE, ST_COMPUTE, ST_DONE
    } state_t;
    state_t state, next_state;

    logic [BATCH_BITS-1:0]         batch_idx;
    logic [CYCLE_BITS-1:0]         input_idx;         // 0..128
    logic                           batch_done;
    logic                           compute_active;
    logic [$clog2(N_OUTPUTS)-1:0]   completed_batch_base;

    // Pipeline: input delayed 1 cycle to align with BRAM read latency
    logic signed [DATA_WIDTH-1:0]   in_val_d1;

    // Registered MAP index from BRAM
    logic [MAP_BITS-1:0]            map_idx [0:PARALLEL_MACS-1];

    // Combinational weight from UNIQUE ROM
    logic signed [DATA_WIDTH-1:0]   weight [0:PARALLEL_MACS-1];

    // MAC accumulators
    logic signed [ACCUM_WIDTH-1:0]  acc_mac [0:PARALLEL_MACS-1];

    // Current input, product
    logic signed [DATA_WIDTH-1:0]   in_val;
    logic signed [35:0]             product [0:PARALLEL_MACS-1];

    logic [11:0]                    bram_addr;
    logic [$clog2(N_OUTPUTS)-1:0]   neuron_base;

    assign neuron_base = batch_idx * PARALLEL_MACS;
    assign bram_addr   = {batch_idx, input_idx[INPUT_BITS-1:0]};
    assign in_val      = fc_in[input_idx[INPUT_BITS-1:0]];

    // =========================================================================
    // Combinational UNIQUE lookup → weight value
    // =========================================================================
    generate
        for (genvar m = 0; m < PARALLEL_MACS; m++) begin : gen_weight_lookup
            assign weight[m] = UNIQUE_FC1_W[map_idx[m]];
        end
    endgenerate

    // =========================================================================
    // Products → DSP48E2
    // =========================================================================
    generate
        for (genvar m = 0; m < PARALLEL_MACS; m++) begin : gen_product
            assign product[m] = in_val_d1 * weight[m];
        end
    endgenerate

    // =========================================================================
    // FSM state register
    // =========================================================================
    always_ff @(posedge clk) begin
        if (rst)
            state <= ST_IDLE;
        else
            state <= next_state;
    end

    // FSM next-state
    always_comb begin
        next_state = state;
        case (state)
            ST_IDLE:    if (start)                                               next_state = ST_COMPUTE;
            ST_COMPUTE: if (batch_done && !compute_active)                        next_state = ST_DONE;
            ST_DONE:                                                               next_state = ST_IDLE;
            default:                                                               next_state = ST_IDLE;
        endcase
    end

    // =========================================================================
    // Datapath control
    // =========================================================================
    always_ff @(posedge clk) begin
        if (rst) begin
            batch_idx            <= '0;
            input_idx            <= '0;
            batch_done           <= 1'b0;
            compute_active       <= 1'b0;
            completed_batch_base <= '0;
            busy                 <= 1'b0;
            done                 <= 1'b0;
            in_val_d1            <= '0;
        end else begin
            done       <= 1'b0;
            batch_done <= 1'b0;

            case (state)

                ST_IDLE: begin
                    busy <= 1'b0;
                    if (start) begin
                        batch_idx      <= '0;
                        input_idx      <= '0;
                        compute_active <= 1'b1;
                        busy           <= 1'b1;
                        in_val_d1      <= '0;
                    end
                end

                ST_COMPUTE: begin
                    busy <= 1'b1;

                    // Pipeline: capture fc_in so it aligns with BRAM weight output
                    if (compute_active && input_idx < N_INPUTS)
                        in_val_d1 <= fc_in[input_idx[INPUT_BITS-1:0]];

                    if (compute_active) begin
                        if (input_idx == BATCH_CYCLES - 1) begin   // input_idx == 128
                            completed_batch_base <= batch_idx * PARALLEL_MACS;
                            input_idx            <= '0;
                            in_val_d1            <= '0;
                            if (batch_idx == NUM_BATCHES - 1) begin
                                compute_active <= 1'b0;
                                batch_done     <= 1'b1;
                            end else begin
                                batch_idx  <= batch_idx + 1'b1;
                                batch_done <= 1'b1;
                            end
                        end else begin
                            input_idx <= input_idx + 1'b1;
                        end
                    end
                end

                ST_DONE: begin
                    done <= 1'b1;
                    busy <= 1'b0;
                end

                default: ;
            endcase
        end
    end

    // =========================================================================
    // BRAM registered reads — 8 parallel, 1-cycle latency each
    // =========================================================================
    always_ff @(posedge clk) begin
        if (state == ST_COMPUTE && compute_active && input_idx < N_INPUTS) begin
            map_idx[0] <= fc1_map_bram_0[bram_addr];
            map_idx[1] <= fc1_map_bram_1[bram_addr];
            map_idx[2] <= fc1_map_bram_2[bram_addr];
            map_idx[3] <= fc1_map_bram_3[bram_addr];
            map_idx[4] <= fc1_map_bram_4[bram_addr];
            map_idx[5] <= fc1_map_bram_5[bram_addr];
            map_idx[6] <= fc1_map_bram_6[bram_addr];
            map_idx[7] <= fc1_map_bram_7[bram_addr];
        end else if (rst || (state == ST_IDLE && start)) begin
            for (int m = 0; m < PARALLEL_MACS; m++) map_idx[m] <= '0;
        end
    end

    // =========================================================================
    // MAC accumulators — reset at batch start, accumulate each cycle
    //   input_idx = 0:          setup cycle (BRAM read, no MAC)
    //   input_idx = 1:          first MAC (acc = product, overwrite old)
    //   input_idx = 2..128:     accumulate (acc = acc + product)
    // =========================================================================
    always_ff @(posedge clk) begin
        if (rst)
            for (int m = 0; m < PARALLEL_MACS; m++) acc_mac[m] <= '0;
        else if (state == ST_IDLE && start)
            for (int m = 0; m < PARALLEL_MACS; m++) acc_mac[m] <= '0;
        else if (state == ST_COMPUTE && compute_active && input_idx >= 1) begin
            if (input_idx == 1)
                for (int m = 0; m < PARALLEL_MACS; m++)
                    acc_mac[m] <= $signed(product[m]);
            else
                for (int m = 0; m < PARALLEL_MACS; m++)
                    acc_mac[m] <= acc_mac[m] + $signed(product[m]);
        end
    end

    // =========================================================================
    // Batch complete — bias, normalise (>>>FRAC_BITS), ReLU, store
    // =========================================================================
    always_ff @(posedge clk) begin
        if (rst) begin
            for (int o = 0; o < N_OUTPUTS; o++) fc_out[o] <= '0;
        end else if ((state == ST_COMPUTE || state == ST_DONE) && batch_done) begin
            logic signed [ACCUM_WIDTH-1:0] bias_wide, bias_aligned, total;
            logic signed [DATA_WIDTH-1:0]  result;
            int unsigned neuron;
            for (int m = 0; m < PARALLEL_MACS; m++) begin
                neuron       = completed_batch_base + m;
                bias_wide    = $signed(FC1_BIAS[neuron]);
                bias_aligned = bias_wide <<< FRAC_BITS;
                total        = acc_mac[m] + bias_aligned;
                result       = total >>> FRAC_BITS;
                if (result < 0) result = '0;
                fc_out[neuron] <= result;
            end
        end
    end

endmodule
