//===========================================================
// File        : fc2_layer.sv
// Purpose     : Fully-connected layer 2: 256 inputs -> 4 outputs
//               (class logits, no ReLU - this is the final layer).
//               All 4 output neurons computed in PARALLEL with a single
//               single-batch MAC array (no time-multiplexing needed,
//               since PARALLEL_MACS == N_OUTPUTS here). Q_.9 fixed-point.
//               Weight deduplication: 9-bit MAP indices in 4 BRAMs point
//               into a 387-value combinational LUT ROM.
//               1-cycle BRAM pipeline: 257 cycles total (1 setup + 256 MAC).
// Used in     : top-level inference pipeline (consumes fc1_layer's output)
//===========================================================
// Written by  : Ahmad Khattab
// Revised by  : Eman Yasser
// Last edit   : 2026-07-06
//===========================================================

`ifndef FC2_LAYER_SV
`define FC2_LAYER_SV

module fc2_layer
#(
    parameter int DATA_WIDTH  = 18,   // activation / weight / bias width, Q_.FRAC_BITS
    parameter int FRAC_BITS   = 9,    // number of fractional bits in the fixed-point format
    parameter int N_INPUTS    = 256,  // number of input activations to this layer
    parameter int N_OUTPUTS   = 4,    // number of output neurons (class logits) in this layer
    parameter int ACCUM_WIDTH = 48    // MAC accumulator width (headroom above DATA_WIDTH)
)
(
    //=======================================================
    // Controls
    //=======================================================
    input  wire logic                      clk,
    input  wire logic                      arst_n,    
    input  wire logic                      start,    
    //=======================================================
    // Inputs
    //=======================================================
    input  wire signed [DATA_WIDTH-1:0]    fc_in  [0:N_INPUTS-1],
    //=======================================================
    // Outputs
    //=======================================================
    output reg   signed [DATA_WIDTH-1:0]   fc_out [0:N_OUTPUTS-1],  
    output reg                             done,                    
    output reg                             busy                    
);

    //=======================================================
    // Weight Codebook (include)
    //=======================================================
    // 387 distinct weight values used across the whole layer, generated by
    // gen_unique_includes.py from the trained/quantized weight matrix.
    `include "UNIQUE_FC2_W.svh"

    //=======================================================
    // Local Parameters
    //=======================================================
    // Biases - one per OUTPUT NEURON (4 total, one per class logit).
    localparam logic signed [DATA_WIDTH-1:0] FC2_BIAS [N_OUTPUTS] = '{
        18'h00011, 18'h3FFDD, 18'h3FF69, 18'h0009A
    };

    // BRAM / timing sizing.
    //   MAP_BITS      : width of one map index (pointer into the 387-entry
    //                   weight codebook). 9 bits because 2^9 = 512 >= 387.
    //   BRAM_DEPTH    : map indices ONE BRAM must hold = N_INPUTS = 256
    //                   (one entry per input, since this layer has no
    //                   batching - every neuron is computed in the same pass).
    //   PARALLEL_MACS : this layer builds one MAC lane PER OUTPUT NEURON
    //                   (4 lanes total), since N_OUTPUTS is small enough
    //                   to fit in parallel with no time-multiplexing -
    //                   unlike fc1_layer, there is only ever 1 batch here.
    //   BATCH_CYCLES  : 1 setup cycle (BRAM read only, no math yet)
    //                   + 256 cycles (one per input, pipelined) = 257.
    localparam int MAP_BITS      = 9;
    localparam int BRAM_DEPTH    = N_INPUTS;                 // 256
    localparam int PARALLEL_MACS = N_OUTPUTS;                // 4
    localparam int INPUT_BITS    = $clog2(N_INPUTS);         // bits to index 0..255
    localparam int BATCH_CYCLES  = N_INPUTS + 1;             // 257
    localparam int CYCLE_BITS    = $clog2(BATCH_CYCLES);     // bits to count 0..256

    //=======================================================
    // Internals
    //=======================================================
    //   Map-index BRAMs - one per output neuron (4 total), since all 4 output
    //   neurons are computed simultaneously in a single pass (no batching).
    //   Each BRAM: 256 entries x 9 bits - fits easily in a BRAM18/BRAM36.
    //   NOTE: previously stored as one array-of-arrays (fc2_map_bram[0:3]
    //   [0:255]) with a generate-for loop doing per-lane $readmemh into
    //   fc2_map_bram[b]. Vivado's xsim does not reliably keep each
    //   generate instance's $readmemh scoped to just its own slice of a
    //   shared 2D unpacked array - all 4 lanes ended up reading back the
    //   SAME weight sequence at runtime (verified: acc_mac identical
    //   across all 4 lanes). Declaring 4 fully independent, separately
    //   named memories below removes any array-slice aliasing for the
    //   simulator to get wrong.
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc2_map_bram_0 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc2_map_bram_1 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc2_map_bram_2 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc2_map_bram_3 [0:BRAM_DEPTH-1];

    //=======================================================
    // FSM
    //=======================================================
    //   ST_IDLE    -> waits for `start`
    //   ST_COMPUTE -> runs the single pass over all 256 inputs, 257 cycles
    //   ST_DONE    -> exactly 1 cycle, pulses `done`, then returns to ST_IDLE
    typedef enum logic [1:0] {
        ST_IDLE, ST_COMPUTE, ST_DONE
    } state_t;
    state_t state, next_state;

    // Counters / control bits.
    logic [CYCLE_BITS-1:0]   input_idx;      // cycle counter (0..256)
    logic                    compute_done;   // 1-cycle pulse: the single pass just finished

    // Pipeline registers.
    logic signed [DATA_WIDTH-1:0]   in_val_d1;                     // fc_in delayed 1 cycle to align with BRAM read latency
    logic [MAP_BITS-1:0]            map_idx  [0:PARALLEL_MACS-1];  // registered BRAM output (per lane)
    logic signed [ACCUM_WIDTH-1:0]  acc_mac  [0:PARALLEL_MACS-1];  // running dot-product sum (per lane)

    // Continuous (assign-fed) nets.
    wire logic signed [DATA_WIDTH-1:0]   in_val;                         // current (undelayed) input value
    wire logic signed [DATA_WIDTH-1:0]   weight   [0:PARALLEL_MACS-1];   // weight looked up from codebook
    wire logic signed [35:0]             product  [0:PARALLEL_MACS-1];   // in_val_d1 * weight (18b*18b=36b)

    assign in_val = fc_in[input_idx[INPUT_BITS-1:0]];   // input value for this cycle

    //=======================================================
    // weight_lookup
    //=======================================================
    // Turn each lane's 9-bit map index into the real weight value by looking
    // it up in the shared 387-entry codebook
    generate
        for (genvar m = 0; m < PARALLEL_MACS; m++) begin : gen_weight_lookup
            assign weight[m] = UNIQUE_FC2_W[map_idx[m]];
        end
    endgenerate

    //=======================================================
    // product_compute
    //=======================================================
    // Multiply the (delayed) input by each lane's weight. Maps onto the
    // FPGA's hardened DSP48E2 multiplier blocks.
    generate
        for (genvar m = 0; m < PARALLEL_MACS; m++) begin : gen_product
            assign product[m] = in_val_d1 * weight[m];
        end
    endgenerate

    //=======================================================
    // fsm_state_register
    //=======================================================
    always_ff @(posedge clk or negedge arst_n)
    begin
        if (!arst_n)
            state <= ST_IDLE;
        else
            state <= next_state;
    end

    //=======================================================
    // fsm_next_state
    //=======================================================
    always_comb
    begin
        //===================================================
        // Defaults
        //===================================================
        next_state = state;  

        //===================================================
        // State transitions
        //===================================================
        case (state)
            // Leave IDLE the moment `start` is asserted.
            ST_IDLE:
                if (start)
                    next_state = ST_COMPUTE;

            // Leave COMPUTE once the single pass over all 256 inputs is done.
            ST_COMPUTE:
                if (compute_done)
                    next_state = ST_DONE;

            // DONE always lasts exactly one cycle, then back to IDLE.
            ST_DONE:
                next_state = ST_IDLE;

            default:
                next_state = ST_IDLE;
        endcase
    end

    //=======================================================
    // datapath_control
    //=======================================================
    // Walks input_idx 0 -> 256 once per full layer pass (no batching, unlike
    // fc1_layer, since all 4 output neurons are computed in parallel here).
    always_ff @(posedge clk or negedge arst_n)
    begin
        //===================================================
        // Reset
        //===================================================
        if (!arst_n)
        begin
            input_idx    <= '0;
            compute_done <= 1'b0;
            busy         <= 1'b0;
            done         <= 1'b0;
            in_val_d1    <= '0;
        end
        //===================================================
        // Running
        //===================================================
        else
        begin
            // Both are 1-cycle pulses: clear every cycle by default, then
            // re-assert below only on the specific cycle where they should fire.
            done         <= 1'b0;
            compute_done <= 1'b0;

            case (state)

                //===============================================
                // ST_IDLE
                //===============================================
                ST_IDLE:
                begin
                    busy <= 1'b0;
                    if (start)
                    begin
                        input_idx <= '0;
                        busy      <= 1'b1;
                        in_val_d1 <= '0;
                    end
                end

                //===============================================
                // ST_COMPUTE
                //===============================================
                ST_COMPUTE:
                begin
                    busy <= 1'b1;

                    // Latch the current input so it's available NEXT cycle,
                    // aligned with the weight that the BRAM read (issued this
                    // cycle) will produce.
                    if (input_idx < N_INPUTS)
                        in_val_d1 <= fc_in[input_idx[INPUT_BITS-1:0]];

                    // input_idx == 256 means: all 256 MAC cycles are done.
                    if (input_idx == BATCH_CYCLES - 1)
                    begin
                        input_idx    <= '0;
                        compute_done <= 1'b1;
                        in_val_d1    <= '0;
                    end
                    else
                    begin
                        input_idx <= input_idx + 1'b1;
                    end
                end

                //===============================================
                // ST_DONE
                //===============================================
                ST_DONE:
                begin
                    done <= 1'b1;   // tell the outside world the pass finished
                    busy <= 1'b0;
                end

                default: ;
            endcase
        end
    end

    //=======================================================
    // bram_read_stage
    //=======================================================
    // Registered, 1-cycle latency, 4 lanes in parallel (one per output
    // neuron). Reads happen for input_idx 0..255 (the "setup" cycle
    // input_idx==0 is included, since its result is needed by the time
    // input_idx==1 arrives).
    // Asynchronous, active-LOW reset: checked FIRST in priority so that an
    // async reset always wins, even if `state`/`input_idx` haven't settled
    // to their post-reset values yet within the same simulation delta.
    //
    // NOTE: manually unrolled (not a generate-for over a shared 2D array
    // slice) for the same reason the memories above are separate named
    // signals - see the comment on fc2_map_bram_0..3 above.
    always_ff @(posedge clk or negedge arst_n)
    begin
        if (!arst_n)
            map_idx[0] <= '0;
        else if (state == ST_IDLE && start)
            map_idx[0] <= '0;
        else if (state == ST_COMPUTE && input_idx < N_INPUTS)
            map_idx[0] <= fc2_map_bram_0[input_idx[INPUT_BITS-1:0]];
    end

    always_ff @(posedge clk or negedge arst_n)
    begin
        if (!arst_n)
            map_idx[1] <= '0;
        else if (state == ST_IDLE && start)
            map_idx[1] <= '0;
        else if (state == ST_COMPUTE && input_idx < N_INPUTS)
            map_idx[1] <= fc2_map_bram_1[input_idx[INPUT_BITS-1:0]];
    end

    always_ff @(posedge clk or negedge arst_n)
    begin
        if (!arst_n)
            map_idx[2] <= '0;
        else if (state == ST_IDLE && start)
            map_idx[2] <= '0;
        else if (state == ST_COMPUTE && input_idx < N_INPUTS)
            map_idx[2] <= fc2_map_bram_2[input_idx[INPUT_BITS-1:0]];
    end

    always_ff @(posedge clk or negedge arst_n)
    begin
        if (!arst_n)
            map_idx[3] <= '0;
        else if (state == ST_IDLE && start)
            map_idx[3] <= '0;
        else if (state == ST_COMPUTE && input_idx < N_INPUTS)
            map_idx[3] <= fc2_map_bram_3[input_idx[INPUT_BITS-1:0]];
    end

    //=======================================================
    // mac_accumulate_stage
    //=======================================================
    // input_idx == 0      : setup cycle only (BRAM read in flight) -> no MAC.
    // input_idx == 1      : first REAL product is ready -> OVERWRITE the
    //                        accumulator (implicit clear, no separate reset
    //                        needed since there is only ever one pass).
    // input_idx == 2..256  : normal accumulate: acc += product.
    generate
        for (genvar y = 0; y < PARALLEL_MACS; y++) begin : gen_mac_accumulate
            always_ff @(posedge clk or negedge arst_n)
            begin
                //===========================================
                // Reset / new run
                //===========================================
                if (!arst_n)
                    acc_mac[y] <= '0;
                else if (state == ST_IDLE && start)
                    acc_mac[y] <= '0;
                //===========================================
                // Accumulate
                //===========================================
                else if (state == ST_COMPUTE && input_idx >= 1)
                begin
                    if (input_idx == 1)
                        acc_mac[y] <= ACCUM_WIDTH'($signed(product[y]));
                    else
                        acc_mac[y] <= acc_mac[y] + $signed(ACCUM_WIDTH'(product[y]));
                end
            end
        end
    endgenerate

    //=======================================================
    // completion_stage
    //=======================================================
    // Add bias, rescale, store final output. NO ReLU here - this is the
    // final layer, so outputs are raw class logits (can be negative).
    // Fires once, when `compute_done` pulses at the end of the single pass.
    //
    // Fixed-point note: acc_mac is a sum of (Q_.FRAC_BITS x Q_.FRAC_BITS)
    // products, so its "true" scale is Q_.(2*FRAC_BITS). The bias, however,
    // is stored in plain Q_.FRAC_BITS. To add them correctly, the bias is
    // shifted LEFT by FRAC_BITS first (bias_aligned) to match the
    // accumulator's larger scale. After adding, the sum is shifted RIGHT by
    // FRAC_BITS to bring the result back down to normal Q_.FRAC_BITS output.
    generate
        for (genvar p = 0; p < N_OUTPUTS; p++) begin : gen_completion
            always_ff @(posedge clk or negedge arst_n)
            begin
                //===========================================
                // Reset
                //===========================================
                if (!arst_n)
                    fc_out[p] <= '0;
                //===========================================
                // Bias + rescale + writeback (no ReLU)
                //===========================================
                else if (state == ST_COMPUTE && compute_done)
                begin
                    logic signed [ACCUM_WIDTH-1:0] bias_wide, bias_aligned, total;
                    logic signed [DATA_WIDTH-1:0]  result;

                    bias_wide    <= ACCUM_WIDTH'($signed(FC2_BIAS[p]));  // sign-extend bias to ACCUM_WIDTH
                    bias_aligned <= bias_wide <<< FRAC_BITS;             // rescale bias to match acc_mac's scale
                    total        <= acc_mac[p] + bias_aligned;           // dot-product + bias
                    result       <= DATA_WIDTH'(total >>> FRAC_BITS);    // rescale back down to Q_.FRAC_BITS
                    fc_out[p]   <= result;                              // no ReLU clamp - raw logit output
                end
            end
        end
    endgenerate

    //=======================================================
    // weight_bram_init
    //=======================================================
    // Plain (non-generate) initial blocks loading the 4 independent,
    // separately-named memories declared above - see the comment there
    // for why this replaced the earlier generate-for + 2D-array version.
    initial $readmemh("fc2_map_bram_0.mem", fc2_map_bram_0);
    initial $readmemh("fc2_map_bram_1.mem", fc2_map_bram_1);
    initial $readmemh("fc2_map_bram_2.mem", fc2_map_bram_2);
    initial $readmemh("fc2_map_bram_3.mem", fc2_map_bram_3);

endmodule

`endif // FC2_LAYER_SV