//////////////////////////////////////////////////////////////////////////////////////////////////
// Author    : Ahmad Khattab
// Date      : 5/17/26
// File      : fc2_layer.sv
// Status    : finalized
// Goal      : Fully-connected layer 2: 256 inputs -> 4 outputs (class logits, no ReLU).
//             All 4 output neurons computed in parallel with single-batch MAC array.
//             Q7.10 fixed-point.  Weight deduplication: MAP indices in 4 BRAMs,
//             unique weights (387 values) in combinational LUT ROM.
//             1-cycle BRAM pipeline: 257 cycles total.
//////////////////////////////////////////////////////////////////////////////////////////////////

module fc2_layer #(
    parameter int DATA_WIDTH     = 18,
    parameter int FRAC_BITS      = 10,
    parameter int N_INPUTS       = 256,
    parameter int N_OUTPUTS      = 4,
    parameter int ACCUM_WIDTH    = 48
)(
    input  logic                           clk,
    input  logic                           rst,

    input  logic signed [DATA_WIDTH-1:0]   fc_in  [0:N_INPUTS-1],
    input  logic                           start,

    output logic signed [DATA_WIDTH-1:0]   fc_out [0:N_OUTPUTS-1],
    output logic                           done,
    output logic                           busy
);

    // =========================================================================
    // Unique weight values — generated by gen_unique_includes.py
    // =========================================================================
    `include "UNIQUE_FC2_W.svh"

    // =========================================================================
    // Biases
    // =========================================================================
    localparam logic signed [DATA_WIDTH-1:0] FC2_BIAS [N_OUTPUTS] = '{
        18'h00011, 18'h3FFDD, 18'h3FF69, 18'h0009A
    };

    // =========================================================================
    // BRAM: 4 separate BRAMs for MAP indices
    //   Each BRAM: 256 entries x 9 bits — fits easily in BRAM18/BRAM36
    //   One BRAM per output neuron (4 parallel MACs = all neurons in parallel)
    // =========================================================================
    localparam int MAP_BITS      = 9;
    localparam int BRAM_DEPTH    = N_INPUTS;       // 256
    localparam int PARALLEL_MACS = N_OUTPUTS;       // 4
    localparam int INPUT_BITS    = $clog2(N_INPUTS);
    localparam int BATCH_CYCLES  = N_INPUTS + 1;    // 257
    localparam int CYCLE_BITS    = $clog2(BATCH_CYCLES);

    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc2_map_bram_0 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc2_map_bram_1 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc2_map_bram_2 [0:BRAM_DEPTH-1];
    (* ram_style = "block" *) logic [MAP_BITS-1:0] fc2_map_bram_3 [0:BRAM_DEPTH-1];

    initial begin
        $readmemh("bram_mem/fc2_map_bram_0.mem", fc2_map_bram_0);
        $readmemh("bram_mem/fc2_map_bram_1.mem", fc2_map_bram_1);
        $readmemh("bram_mem/fc2_map_bram_2.mem", fc2_map_bram_2);
        $readmemh("bram_mem/fc2_map_bram_3.mem", fc2_map_bram_3);
    end

    // =========================================================================
    // FSM
    // =========================================================================
    typedef enum logic [1:0] {
        ST_IDLE, ST_COMPUTE, ST_DONE
    } state_t;
    state_t state, next_state;

    logic [CYCLE_BITS-1:0]   input_idx;         // 0..256
    logic                    compute_done;

    // Pipeline: input delayed 1 cycle to align with BRAM read latency
    logic signed [DATA_WIDTH-1:0]  in_val_d1;

    // Registered MAP index from BRAM
    logic [MAP_BITS-1:0]           map_idx [0:PARALLEL_MACS-1];

    // Combinational weight from UNIQUE ROM
    logic signed [DATA_WIDTH-1:0]  weight [0:PARALLEL_MACS-1];

    // MAC accumulators
    logic signed [ACCUM_WIDTH-1:0] acc_mac [0:PARALLEL_MACS-1];

    // Current input, product
    logic signed [DATA_WIDTH-1:0]  in_val;
    logic signed [35:0]            product [0:PARALLEL_MACS-1];

    assign in_val = fc_in[input_idx[INPUT_BITS-1:0]];

    // =========================================================================
    // Combinational UNIQUE lookup → weight value
    // =========================================================================
    generate
        for (genvar m = 0; m < PARALLEL_MACS; m++) begin : gen_weight_lookup
            assign weight[m] = UNIQUE_FC2_W[map_idx[m]];
        end
    endgenerate

    // =========================================================================
    // Products → DSP48E2
    // =========================================================================
    generate
        for (genvar m = 0; m < PARALLEL_MACS; m++) begin : gen_product
            assign product[m] = in_val_d1 * weight[m];
        end
    endgenerate

    // =========================================================================
    // FSM state register
    // =========================================================================
    always_ff @(posedge clk) begin
        if (rst) state <= ST_IDLE;
        else     state <= next_state;
    end

    // FSM next-state
    always_comb begin
        next_state = state;
        case (state)
            ST_IDLE:    if (start)         next_state = ST_COMPUTE;
            ST_COMPUTE: if (compute_done)  next_state = ST_DONE;
            ST_DONE:                       next_state = ST_IDLE;
            default:                       next_state = ST_IDLE;
        endcase
    end

    // =========================================================================
    // Datapath control
    // =========================================================================
    always_ff @(posedge clk) begin
        if (rst) begin
            input_idx    <= '0;
            compute_done <= 1'b0;
            busy         <= 1'b0;
            done         <= 1'b0;
            in_val_d1    <= '0;
        end else begin
            done         <= 1'b0;
            compute_done <= 1'b0;

            case (state)
                ST_IDLE: begin
                    busy <= 1'b0;
                    if (start) begin
                        input_idx <= '0;
                        busy      <= 1'b1;
                        in_val_d1 <= '0;
                    end
                end

                ST_COMPUTE: begin
                    busy <= 1'b1;

                    // Pipeline input for BRAM alignment
                    if (input_idx < N_INPUTS)
                        in_val_d1 <= fc_in[input_idx[INPUT_BITS-1:0]];

                    if (input_idx == BATCH_CYCLES - 1) begin   // input_idx == 256
                        input_idx    <= '0;
                        compute_done <= 1'b1;
                        in_val_d1    <= '0;
                    end else begin
                        input_idx <= input_idx + 1'b1;
                    end
                end

                ST_DONE: begin done <= 1'b1; busy <= 1'b0; end
                default: ;
            endcase
        end
    end

    // =========================================================================
    // BRAM registered reads
    // =========================================================================
    always_ff @(posedge clk) begin
        if (state == ST_COMPUTE && input_idx < N_INPUTS) begin
            map_idx[0] <= fc2_map_bram_0[input_idx[INPUT_BITS-1:0]];
            map_idx[1] <= fc2_map_bram_1[input_idx[INPUT_BITS-1:0]];
            map_idx[2] <= fc2_map_bram_2[input_idx[INPUT_BITS-1:0]];
            map_idx[3] <= fc2_map_bram_3[input_idx[INPUT_BITS-1:0]];
        end else if (rst || (state == ST_IDLE && start)) begin
            for (int m = 0; m < PARALLEL_MACS; m++) map_idx[m] <= '0;
        end
    end

    // =========================================================================
    // MAC accumulators
    //   input_idx = 0:          setup cycle (BRAM read, no MAC)
    //   input_idx = 1:          first MAC (acc = product, overwrite old)
    //   input_idx = 2..256:     accumulate (acc = acc + product)
    // =========================================================================
    always_ff @(posedge clk) begin
        if (rst)
            for (int m = 0; m < PARALLEL_MACS; m++) acc_mac[m] <= '0;
        else if (state == ST_IDLE && start)
            for (int m = 0; m < PARALLEL_MACS; m++) acc_mac[m] <= '0;
        else if (state == ST_COMPUTE && input_idx >= 1) begin
            if (input_idx == 1)
                for (int m = 0; m < PARALLEL_MACS; m++)
                    acc_mac[m] <= $signed(product[m]);
            else
                for (int m = 0; m < PARALLEL_MACS; m++)
                    acc_mac[m] <= acc_mac[m] + $signed(product[m]);
        end
    end

    // =========================================================================
    // Completion — bias add, normalise (>>>FRAC_BITS), store (no ReLU)
    // =========================================================================
    always_ff @(posedge clk) begin
        if (rst) begin
            for (int o = 0; o < N_OUTPUTS; o++) fc_out[o] <= '0;
        end else if (state == ST_COMPUTE && compute_done) begin
            for (int m = 0; m < PARALLEL_MACS; m++) begin
                automatic logic signed [ACCUM_WIDTH-1:0] bias_wide, bias_aligned, total;
                automatic logic signed [DATA_WIDTH-1:0]  result;
                bias_wide    = $signed(FC2_BIAS[m]);
                bias_aligned = bias_wide <<< FRAC_BITS;
                total        = acc_mac[m] + bias_aligned;
                result       = total >>> FRAC_BITS;
                fc_out[m] <= result;
            end
        end
    end

endmodule
