onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /stage1_only_tb/DUT/clk
add wave -noupdate /stage1_only_tb/DUT/rst
add wave -noupdate /stage1_only_tb/DUT/arst_n
add wave -noupdate /stage1_only_tb/DUT/enable
add wave -noupdate /stage1_only_tb/DUT/pixel_mem_wr_en
add wave -noupdate /stage1_only_tb/DUT/pixel_mem_wr_addr
add wave -noupdate /stage1_only_tb/DUT/pixel_mem_wr_data
add wave -noupdate /stage1_only_tb/DUT/start_i
add wave -noupdate /stage1_only_tb/DUT/mem_data_i
add wave -noupdate /stage1_only_tb/DUT/spike_out
add wave -noupdate /stage1_only_tb/DUT/class_logits
add wave -noupdate /stage1_only_tb/DUT/classifier_done
add wave -noupdate /stage1_only_tb/DUT/classifier_busy
add wave -noupdate /stage1_only_tb/DUT/snn_done
add wave -noupdate /stage1_only_tb/DUT/done
add wave -noupdate /stage1_only_tb/DUT/mem_addr_o
add wave -noupdate /stage1_only_tb/DUT/mem_rd_o
add wave -noupdate /stage1_only_tb/DUT/map_done_o
add wave -noupdate /stage1_only_tb/DUT/src_sel
add wave -noupdate /stage1_only_tb/DUT/frame
add wave -noupdate /stage1_only_tb/DUT/stage_sel
add wave -noupdate /stage1_only_tb/DUT/conv2_filter
add wave -noupdate /stage1_only_tb/DUT/conv3_filter
add wave -noupdate /stage1_only_tb/DUT/ctrl_mem_enable
add wave -noupdate /stage1_only_tb/DUT/ctrl_rd_enable
add wave -noupdate /stage1_only_tb/DUT/ctrl_rd_mem_adderss
add wave -noupdate /stage1_only_tb/DUT/ctrl_wr_mem_adderss
add wave -noupdate /stage1_only_tb/DUT/ctrl_zero
add wave -noupdate /stage1_only_tb/DUT/ctrl_zero_sel
add wave -noupdate /stage1_only_tb/DUT/ctrl_padding_flag
add wave -noupdate /stage1_only_tb/DUT/gap_sample_enable
add wave -noupdate /stage1_only_tb/DUT/ctrl_done_load_o
add wave -noupdate /stage1_only_tb/DUT/ctrl_fetch_en_i
add wave -noupdate /stage1_only_tb/DUT/ctrl_next_i
add wave -noupdate /stage1_only_tb/DUT/map_conv_valid_o
add wave -noupdate /stage1_only_tb/DUT/map_conv_pixels_o
add wave -noupdate /stage1_only_tb/DUT/map_conv_done_o
add wave -noupdate /stage1_only_tb/DUT/map_ctrl_done_o
add wave -noupdate /stage1_only_tb/DUT/map_frame_done_o
add wave -noupdate /stage1_only_tb/DUT/map_state_o
add wave -noupdate /stage1_only_tb/DUT/gap_busy
add wave -noupdate /stage1_only_tb/DUT/gap_done
add wave -noupdate /stage1_only_tb/DUT/gap_done_d
add wave -noupdate /stage1_only_tb/DUT/enable_d
add wave -noupdate /stage1_only_tb/DUT/snn_done_d
add wave -noupdate /stage1_only_tb/DUT/fc1_done_d
add wave -noupdate /stage1_only_tb/DUT/spike_mem_wr_en
add wave -noupdate /stage1_only_tb/DUT/spike_mem_wr_data
add wave -noupdate /stage1_only_tb/DUT/pixel_mem_raw
add wave -noupdate /stage1_only_tb/DUT/pixel_mem_data
add wave -noupdate /stage1_only_tb/DUT/spike_mem_data
add wave -noupdate /stage1_only_tb/DUT/conv_bias_param
add wave -noupdate /stage1_only_tb/DUT/mult_weight_param
add wave -noupdate /stage1_only_tb/DUT/add_weight_param
add wave -noupdate /stage1_only_tb/DUT/fc1_in
add wave -noupdate /stage1_only_tb/DUT/fc1_out
add wave -noupdate /stage1_only_tb/DUT/fc2_out
add wave -noupdate /stage1_only_tb/DUT/fc1_start
add wave -noupdate /stage1_only_tb/DUT/fc1_done
add wave -noupdate /stage1_only_tb/DUT/fc1_busy
add wave -noupdate /stage1_only_tb/DUT/fc2_start
add wave -noupdate /stage1_only_tb/DUT/fc2_done
add wave -noupdate /stage1_only_tb/DUT/fc2_busy
add wave -noupdate /stage1_only_tb/DUT/pixels_mapped
add wave -noupdate /stage1_only_tb/DUT/pixels_to_conv
add wave -noupdate /stage1_only_tb/DUT/weights_mapped
add wave -noupdate /stage1_only_tb/DUT/mac_to_connect
add wave -noupdate /stage1_only_tb/DUT/shb_bus
add wave -noupdate /stage1_only_tb/DUT/shaaban_spike_bus
add wave -noupdate /stage1_only_tb/DUT/gap_clear
add wave -noupdate /stage1_only_tb/DUT/u_top_controller/cs
add wave -noupdate /stage1_only_tb/DUT/u_top_controller/ns
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 185
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {1534487 ps} {1535459 ps}
